### ISSUE TITLE
I got stuck

### ISSUE THREAD

**Issue by Masamuneer** [fritzlb/iOS17-JIT-WIN#1]
I tried to keep with the instructions, unfortunately I can't understand the process. Could you do a video or explain exactly what to do after downloading Python please? I just don't know how to run the python jit_enabler_better.py bundle_id

**Comment by fritzlb** [comment]
I’m preparing a short video tutorial right now :)
To answer your question, if you downloaded my code (green button in the corner, download zip) and extracted it, you can simply double click install.bat. 
You can then run python jit_enabler… by opening cmd.exe as administrator, going to the folder everything is extracted in by typing cd C:\Users\yourusername\yourfolder and then pressing enter. Then simply write the python command by typing into your terminal window and pressing enter again

**Comment by Masamuneer** [comment]
Thank you so much, and i'm sorry for the dumb issue, i'm just not experienced in this at all. I'll be trying it again and waiting for that tutorial! :)

**Comment by fritzlb** [comment]
the video is done https://www.youtube.com/watch?v=xtSnHTDtX_M :)
english isn't my first language, I hope you're still able to understand everything
If you have any more questions feel free to ask, else I'm going to close this issue within the next few days

**Comment by Masamuneer** [comment]
Thanks for the tutorial, I've already seen it and followed it! However, I tried to enable the same App you were trying out in the video just to do it exactly the same (PojavLauncher). When I execute the command with the app ID it prompts "Error opening a tunnel..." and can't continue., I tried it with other app ID's and still the same. Any tips?

**Comment by fritzlb** [comment]
Is there anything before the error in your terminal? 
I'd try rebooting the PC (by actually pressing reboot, shutting down and starting again isn't the same bc of windows), when I had a similar issue during development it fixed that

**Comment by Masamuneer** [comment]
Already rebooted, I'll share the full message:
"Started app. PID:
Starting debug server...
2024-03-06 13:58:33 *** ERROR Failed to start service. Possible reasons are:
- If you were trying to access a developer service (developer subcommand):
    - Make sure the DeveloperDiskImage/PersonalizedImage is mounted via:
      > python3 -m pymobiledevice3 mounter auto-mount

    - If your device iOS version >= 17.0:
        - Make sure you passed the --rsd option to the subcommand
          https://github.com/doronz88/pymobiledevice3#working-with-developer-tools-ios--170

- Apple removed this service

- A bug. Please file a bug report:
  https://github.com/doronz88/pymobiledevice3/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Started debug server with connection details:
Run debugging commands...
done."

**Comment by fritzlb** [comment]
oh yeah, I know that bug. Sometimes it occurs and idk why, it's something with pymobiledevice3. Usually rebooting fixes it, else it might be a bad cable, very slow (or no) internet connection, something with windows firewall might be another possibility, ...
also I had this on a PC that didn't have iTunes installed (the version from apple, NOT MS store).
you could try opening a terminal (that open terminal here bat file) and execute `python -m pymobiledevice3 mounter auto-mount`, but I'm not too optimistic it'll change anything.

**Comment by B-Hazem** [comment]
Hey! I had the same issue and actually running the command `python -m pymobiledevice3 mounter auto-mount` while having my phone plugged in actually worked for me (I have an Iphone 11 with IOS 17.4)
It showed `pymobiledevice3.cli.mounter[14268] INFO DeveloperDiskImage mounted successfully` as the last message.

After executing that command and relaunching the python script, I got stuck on "starting tunel to device" (even ctrl+c wouldn't kill the script). The fix I found is to run `python -m pymobiledevice3 remote start-tunnel` waiting for the tunnel to get created and then ctrl-c and executing the script.
Everything worked perfectly just the "Run debugging commands" took a lot of time (maybe cause first time idk) but it worked (used dolphinios beta from alt-store and it worked great!)

Hopefully I was clear, and it could help anyone :)

**Comment by fritzlb** [comment]
That’s interesting. Thanks for the feedback, then I’m going to try to implement that developerdiskimage automount command into my script :)
The thing with the script getting stuck with starting the tunnel might be a bug, I think that could be fixed by adding a timeout or something, I’ll take a look at that.

running the debugging commands sadly takes quite a while and I haven’t found a fix yet

**Comment by fritzlb** [comment]
Okay, pythons subprocess library doesn't support timeouts so I just added a print statement with instructions on what to do if it hangs
for the rest, I added better error messages :)
also now the diskimage gets mounted manually, just to be sure everything works.

**Comment by Masamuneer** [comment]
> Hey! I had the same issue and actually running the command `python -m pymobiledevice3 mounter auto-mount` while having my phone plugged in actually worked for me (I have an Iphone 11 with IOS 17.4) It showed `pymobiledevice3.cli.mounter[14268] INFO DeveloperDiskImage mounted successfully` as the last message.
> 
> After executing that command and relaunching the python script, I got stuck on "starting tunel to device" (even ctrl+c wouldn't kill the script). The fix I found is to run `python -m pymobiledevice3 remote start-tunnel` waiting for the tunnel to get created and then ctrl-c and executing the script. Everything worked perfectly just the "Run debugging commands" took a lot of time (maybe cause first time idk) but it worked (used dolphinios beta from alt-store and it worked great!)
> 
> Hopefully I was clear, and it could help anyone :)

Thank you both! I tried using this command and it did something alright. However, after adding it, it won't let me keep writing in the terminal, it just says that the tunnel was created and then "Use the follow connection option: - -rsd fd7c:439e:9a37: :1 57101"

**Comment by fritzlb** [comment]
yeah, that's expected. Close the tunnel (CTRL + C) and try running the script again, only the tunnel isn't enough for JIT
also, maybe re-download the script from github and double click install.bat again, I improved it a few hours ago :)

technical info: my script actually starts the tunnel, mounts the developerdiskimage, starts the app you specified, starts a debugserver and then connects lldb, a debugger, to your app. By connecting the debugger JIT gets enabled, then the debugger disconnects.

**Comment by fritzlb** [comment]
Just to make sure, the script did say "done" and JIT didn't work? Without any errors?

**Comment by KarlosGigabreak** [comment]
![image](https://github.com/fritzlb/iOS17-JIT-WIN/assets/16749829/ecdc4fdd-a74b-43b8-a01a-da8a197c9d57)
Hi, first thank you for you work, im stuk in this step, any help plz 

```
Traceback (most recent call last):
  File "C:\Users\USUARI~1\Desktop\IOS17-~1\IOS17-~1\jit_enabler_better.py", line 110, in <module>
    lldb_process = subprocess.Popen(cmd_lldb, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, text=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\UsuarioLap\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\UsuarioLap\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
```

**Comment by fritzlb** [comment]
it seems like lldb wasn't found... could you check that lldb does exist on your system? it should be inside the folder you're in and then llvm-mingw-20231128-msvcrt-x86_64/bin/lldb.exe
if it is missing, try re-running install.bat.

**Comment by KarlosGigabreak** [comment]
> it seems like lldb wasn't found... could you check that lldb does exist on your system? it should be inside the folder you're in and then llvm-mingw-20231128-msvcrt-x86_64/bin/lldb.exe if it is missing, try re-running install.bat.

You are right, I re run install.bat in admin mode and everything works fine, thank you!

**Comment by Masamuneer** [comment]
> Just to make sure, the script did say "done" and JIT didn't work? Without any errors? Could you then maybe provide the full terminal output of the script?

Here's the script:
"Getting bundle ID...
Got bundle ID: org.provenance-emu.provenance.49P3K55S59
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd7c:7240:fea6::1 57111
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Started app. PID: 11891
Starting debug server...
Started debug server with connection details: [fd7c:7240:fea6::1]:51106
Run debugging commands...
This might take a few minutes.
done."

After this, whenever I try importing ROMs in Provenance it just crashes the app. Similar happened with PojavLauncher, but in there it just said JIT could not be enabled in the app.

**Comment by fritzlb** [comment]
You did install your apps using a supported install method, right? According to the output I think my script is working, so a debugger is being attached, still JIT doesn't work. That might indicate you're not using something like Altstore or sideloadly but rather an online signing service. 
Also, on which ios version are you on?
And did you try something like UTM? UTMs implementation of JIT should be pretty robust

**Comment by Masamuneer** [comment]
Yes, I did. I wouldn’t know any other unofficial method to do it anyways, it was all following the guides step by step. Of course, with a Windows OS though.

**Comment by Masamuneer** [comment]
Since today, I’m in the last version. I was holding in the previous one, for this, just to be safe but now I’m in the last one though.

**Comment by fritzlb** [comment]
Is there any chance you could try this build of PojavLauncher? https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/7697198561
scroll down and download the non-slimmed version for iOS
