### ISSUE TITLE
error when trying to run python jit_enabler_better.py

### ISSUE THREAD

**Issue by Mason11252** [fritzlb/iOS17-JIT-WIN#11]
i get this error message when trying to run python jit_enabler_better.py in the terminal. 
heres the full error message:
C:\Users\micha\DOWNLO~1\IOS17-~1\IOS17-~1>python jit_enabler_better.py net.kdt.pojavlauncher.37WS4Y3AULL
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by fritzlb** [comment]
Thank you for the error message! :)
Please make sure to install python and add it to PATH. Download the python installer from python.org/downloads, execute it and make sure to set the checkbox "Add Python to PATH" right at the beginning.
I won't be able to assist any further, so I'll close this now as this isn't related to the script but rather to installing python. If there's anything not working with the script, feel free to either re-open this issue or create a new one.
