### ISSUE TITLE
Script runs without issues but JIT doesn't get enabled properly

### ISSUE THREAD

**Issue by Hamblock** [fritzlb/iOS17-JIT-WIN#13]
Getting bundle ID...
Got bundle ID: com.antique.Limon.MZ42LYKXWW
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd99:e203:894b::1 49186
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Started app. PID: 2666
Starting debug server...
Started debug server with connection details: [fd99:e203:894b::1]:50088
Run debugging commands...
This might take a few minutes.
done.

After all of that it doesnt open the jit on my ipad ( the app is limon )

**Comment by fritzlb** [comment]
Does anything happen on your ipad if the script runs?
In case the app freezes for a moment (about 20s to 3min), my script did everything right and either your app doesn't support JIT by attaching a debugger for a moment or there's a bug with the app/ios version you're using.
If the app doesn't freeze at all, could you try a different app that's already been tested? If it doesn't work with lets say UTM, the script is at fault. If it does, something's wrong with the app.

**Comment by Hamblock** [comment]
The app does freeze till the the terminal says « done. » but there is no jit on the app…

**Comment by SansYT2017** [comment]
> The app does freeze till the the terminal says « done. » but there is no jit on the app…

Same happens to me with the same App

**Comment by Hamblock** [comment]
But the jit activated two times.. once with majoras mask 3d and once with ssb for 3ds…

**Comment by Hamblock** [comment]
[ Got a solution ] 
The app i use ( Limon ) lets you use jit only on a 3DS model. Not a New 3DS one. So if you are trying to open JIT on Limon make sure you have Old 3DS model on.

**Comment by fritzlb** [comment]
Thank you for your input, then this issue is related to the app. I’ll close this for now, if there’s anything wrong with that app I’d suggest contacting the developers of that app :)

**Comment by Hamblock** [comment]
Thanks
