### ISSUE TITLE
python not found error

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [fritzlb/iOS17-JIT-WIN#15]
I wanted to enable jit on my 17.4 14 pro max, and it said Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases. Do you have any solutions?
C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>set "params="

C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>cd /d "C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\"   && (if exist "C:\Users\chris\AppData\Local\Temp\getadmin.vbs" del "C:\Users\chris\AppData\Local\Temp\getadmin.vbs"  )  && fsutil dirty query C:   1>nul 2>nul  || (echo Set UAC = CreateObject("Shell.Application") : UAC.ShellExecute "cmd.exe", "/k cd ""C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\"" && ""C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\OPENTE~1.BAT"" ", "", "runas", 1   1>>"C:\Users\chris\AppData\Local\Temp\getadmin.vbs"  && "C:\Users\chris\AppData\Local\Temp\getadmin.vbs"   && exit /B  )

C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>python jit_enabler_better.py com.libretro.RetroArchiOS11.LYYWPSCS2Y
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by fritzlb** [comment]
I guess you already found a solution but if not install python and add it to PATH
