### ISSUE TITLE
ModuleNotFoundError: No module named 'pymobiledevice3'

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [fritzlb/iOS17-JIT-WIN#16]
I'm running my ios 17.4 14 pro max on windows 11 pro and i'm not able to enable jit even though i followed your tutorial and installed everything. unfortunately, I'm curious to know what I could know to fix this problem.
C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>set "params="

C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>cd /d "C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\"   && (if exist "C:\Users\chris\AppData\Local\Temp\getadmin.vbs" del "C:\Users\chris\AppData\Local\Temp\getadmin.vbs"  )  && fsutil dirty query C:   1>nul 2>nul  || (echo Set UAC = CreateObject("Shell.Application") : UAC.ShellExecute "cmd.exe", "/k cd ""C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\"" && ""C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\OPENTE~1.BAT"" ", "", "runas", 1   1>>"C:\Users\chris\AppData\Local\Temp\getadmin.vbs"  && "C:\Users\chris\AppData\Local\Temp\getadmin.vbs"   && exit /B  )

C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>python jit_enabler_better.py me.oatmealdome.DolphiniOS-njb-patreon-beta.LYYWPSCS2Y True
Traceback (most recent call last):
  File "C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\jit_enabler_better.py", line 5, in <module>
    import pymobiledevice3
ModuleNotFoundError: No module named 'pymobiledevice3'

C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>A dozen cookie boogie robots
'A' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>
C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>python jit_enabler_better.py com.libretro.RetroArchiOS11.LYYWPSCS2Y
Traceback (most recent call last):
  File "C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\jit_enabler_better.py", line 5, in <module>
    import pymobiledevice3
ModuleNotFoundError: No module named 'pymobiledevice3'

C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>python jit_enabler_better.py

**Comment by Hamblock** [comment]
run install.bat again to download pymobiledevice3

**Comment by fritzlb** [comment]
You can also try running install_slow.bat or execute pip install pymobiledevice3.

**Comment by Hamblock** [comment]
How to pip install?

**Comment by Iamthebestintheworld222** [comment]
how long will the slow install take?

**Comment by fritzlb** [comment]
Only a few minutes, but still a lot longer than the regular install

**Comment by Iamthebestintheworld222** [comment]
it says
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by fritzlb** [comment]
Pip should install together with python, seems like something went wrong there. If you did recently install python (and added it to path ofc) re-opening every terminal window should do the job (which happens automatically by rebooting, that's one of the reasons I implemented that popup tbh).
I didn't develop python though, so if the script isn't working once python and pip are properly installed feel free to share the terminal output again :)

**Comment by Iamthebestintheworld222** [comment]
I looked up a tutorial on youtube, and it worked. I'll try it now.

**Comment by Iamthebestintheworld222** [comment]
i used pip instead of python, and i got this error.
ERROR: unknown command "jit_enabler_better.py"

**Comment by fritzlb** [comment]
No, that's not how it works. Pip is used to install python packages like pymobiledevice3 which is required by the JIT script. 
Python actually runs scripts like jit_enabler_better.py.
You need to execute the commands exactly as described in the Readme file (or the video)

**Comment by Iamthebestintheworld222** [comment]
I installed pymobiledevice3, now to find out if it finally works or not.

**Comment by Iamthebestintheworld222** [comment]
I was able to get it to work, then there's this problem.
C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>cd /d "C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\"   && (if exist "C:\Users\chris\AppData\Local\Temp\getadmin.vbs" del "C:\Users\chris\AppData\Local\Temp\getadmin.vbs"  )  && fsutil dirty query C:   1>nul 2>nul  || (echo Set UAC = CreateObject("Shell.Application") : UAC.ShellExecute "cmd.exe", "/k cd ""C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\"" && ""C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1\OPENTE~1.BAT"" ", "", "runas", 1   1>>"C:\Users\chris\AppData\Local\Temp\getadmin.vbs"  && "C:\Users\chris\AppData\Local\Temp\getadmin.vbs"   && exit /B  )

C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>python jit_enabler_better.py com.libretro.RetroArchiOS11.LYYWPSCS2Y
Getting bundle ID...
Got bundle ID: com.libretro.RetroArchiOS11.LYYWPSCS2Y
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
It seems like your device isn't connected. : [b'\x1b[32m2024-03-16 08:13:52\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34mwintun[6232]\x1b[0m \x1b[1;30mINFO\x1b[0m WeTestUsbFilter driver not exists or expired.\r\n', b'\x1b[32m2024-03-16 08:13:52\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34mwintun[6232]\x1b[0m \x1b[1;30mINFO\x1b[0m Installing WeTestUsbFilter driver\r\n', b'\x1b[32m2024-03-16 08:14:05\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34mwintun[6232]\x1b[0m \x1b[1;30mINFO\x1b[0m Install WeTestUsbFilter completely, exit: 3010\r\n', b'\x1b[32m2024-03-16 08:14:05\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34mwintun[6232]\x1b[0m \x1b[1;30mINFO\x1b[0m WeTestUsbNcm driver not exists or expired.\r\n', b'\x1b[32m2024-03-16 08:14:05\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34mwintun[6232]\x1b[0m \x1b[1;30mINFO\x1b[0m Installing win11_WeTestUsbNcm driver\r\n', b'\x1b[32m2024-03-16 08:14:05\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34mwintun[6232]\x1b[0m \x1b[1;30mINFO\x1b[0m Install win11_WeTestUsbNcm completely, exit: 0\r\n', b'\x1b[32m2024-03-16 08:14:07\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34m__main__[6232]\x1b[0m \x1b[1;30mERROR\x1b[0m \x1b[31mDevice is not connected\x1b[0m\r\n']

C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>python jit_enabler_better.py me.oatmealdome.DolphiniOS-njb-patreon-beta.LYYWPSCS2Y
Getting bundle ID...
Got bundle ID: me.oatmealdome.DolphiniOS-njb-patreon-beta.LYYWPSCS2Y
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
It seems like your device isn't connected. : [b'\x1b[32m2024-03-16 08:15:05\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34mwintun[17880]\x1b[0m \x1b[1;30mINFO\x1b[0m WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.\r\n', b'\x1b[32m2024-03-16 08:15:05\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34mwintun[17880]\x1b[0m \x1b[1;30mINFO\x1b[0m WeTestUsbNcm driver use current version: 11.38.34.492, [11.36.59.886] tested.\r\n', b'\x1b[32m2024-03-16 08:15:05\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34mwintun[17880]\x1b[0m \x1b[1;30mINFO\x1b[0m use existing WeTestUsbFilter driver.\r\n', b'\x1b[32m2024-03-16 08:15:05\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34mwintun[17880]\x1b[0m \x1b[1;30mINFO\x1b[0m use existing WeTestUsbNcm driver.\r\n', b'\x1b[32m2024-03-16 08:15:07\x1b[0m \x1b[35miwillcatch250\x1b[0m \x1b[34m__main__[17880]\x1b[0m \x1b[1;30mERROR\x1b[0m \x1b[31mDevice is not connected\x1b[0m\r\n']

C:\Users\matth\DOWNLO~1\IOS17-~1\IOS17-~1>

**Comment by Iamthebestintheworld222** [comment]
I plugged it back in, and it did work. I found the problem from what i was curious about before. I didn't have the correctly installed stuff yet.

**Comment by fritzlb** [comment]
I'm glad it works :)
