### ISSUE TITLE
Error mounting DiskImage : Failed to connect to usbmuxd

### ISSUE THREAD

**Issue by Clyxos** [fritzlb/iOS17-JIT-WIN#17]
Hi, 
    I was interested in trying out this script. I installed python and ran install_slow.bat. However, when I try to run the main python script, I get the following error:

Getting bundle ID...
Got bundle ID: com.libretro.RetroArchiOS11.38G33N2CT3
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd46:4efe:3db2::1 55905
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Error mounting DiskImage : 2024-03-16 23:52:38 DESKTOP-BB7PMLT __main__[3068] ERROR Failed to connect to usbmuxd socket. Make sure it's running.

If you know a solution, please respond! Thanks!

**Comment by fritzlb** [comment]
Probably installing iTunes directly from Apple fixes that :)
The MS Store version might not work, I didn't test

**Comment by Clyxos** [comment]
I did have iTunes installed from Apple. However, adding True to the end actually fixed it for some reason. Still, thank you for the quick response!

**Comment by fritzlb** [comment]
Interesting, in theory that shouldn't change anything, I'll try to investigate that.
I'm glad it works for you :)
