### ISSUE TITLE
WinError 2 系统找不到指定的文件。

### ISSUE THREAD

**Issue by system-jiangnan** [fritzlb/iOS17-JIT-WIN#18]
I'm Chinese, so it may be difficult for us to communicate.
After I opened "open terminal here.bat", the cmd window flashed and then it closed. I can't enter instructions there.

I opened the cmd window separately, located the location of the program, and entered the command, and there was the following error.

C:\Users\Administrator\Desktop\iOS17-JIT-WIN-main>python jit_enabler_better.py net.kdt.pojavlauncher.NZK3UY8AAX
Getting bundle ID...
Got bundle ID: net.kdt.pojavlauncher.NZK3UY8AAX
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd20:bb53:5cbd::1 60723
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Started app. PID: 1375
Starting debug server...
Started debug server with connection details: [fd20:bb53:5cbd::1]:53748
Run debugging commands...
This might take a few minutes.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\iOS17-JIT-WIN-main\jit_enabler_better.py", line 129, in <module>
    lldb_process = subprocess.Popen(cmd_lldb, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, text=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。(The system cannot find the specified file.)

**Comment by fritzlb** [comment]
You can probably fix that by running install_slow.bat (just by double clicking)

**Comment by system-jiangnan** [comment]
I seem to know why I can't find the file. Will a temporary file be generated on disk D at runtime? I don't have a D disk.

**Comment by system-jiangnan** [comment]
I found the command "cd /d" in "open terminal here.bat". I tried cd /c, but it didn't work. I think it may be that the region is different, and the command usage is also different.

**Comment by fritzlb** [comment]
The install script downloads files for lldb, a debugger which can then connect to the ios app to grant JIT privileges. Those files haven't been found by the python script. 
Please double click install_slow.bat.bat. It'll fix everything automatically.

**Comment by system-jiangnan** [comment]
Oh, I almost forgot to tell you that I tried it yesterday, but it's still the same.

**Comment by system-jiangnan** [comment]
I have tried to reinstall this program and python four or five times, but it still doesn't work. :(

**Comment by system-jiangnan** [comment]
If you can visit this website, then you can go in and see the details of my error: https://b23.tv/RPaSSwH

**Comment by fritzlb** [comment]
I'll take a look at that in a moment. 
Your windows version probably doesn't have the tar command for whatever reason so install_slow.bat does the right thing. 
For the terminal, I only tested it while being logged in as administrator. Maybe that's an issue? Or your PC has vbs scripts blocked or sth?

**Comment by system-jiangnan** [comment]
Oh, I'm using my own streamlined Windows 11, version 22H2. But it's not very likely to streamline what you said. Because that's the instruction.

**Comment by system-jiangnan** [comment]
I just created an original Windows 11 virtual machine and found it ready to use. It's my computer system. Thank you for your trouble.

**Comment by fritzlb** [comment]
Great, thanks for the update!
