### ISSUE TITLE
 Can jit be started via wifi or 4g?(no usb)

### ISSUE THREAD

**Issue by whaleboss** [fritzlb/iOS17-JIT-WIN#19]
This project is very good and useful for me
What is the reason that restricts jit to being able to be started only through usb?
Thanks a lot

**Comment by fritzlb** [comment]
Currently pymobiledevice3 only supports wired connections, at least for iOS 17+. Their roadmap does include adding wireless support (WiFi) with a PC in the same local network. 
also I assume someday libimobiledevice will finally work with iOS 17 Developer Tools, then adding wireless support is trivial :)
