### ISSUE TITLE
It gives me an error :C

### ISSUE THREAD

**Issue by SansYT2017** [fritzlb/iOS17-JIT-WIN#2]
When I try it on my Ipad 11 with IOS 17.3 it gives me this error: 

2024-03-06 00:00:48 DESKTOP-1NA7TE5 __main__[17724] ERROR Failed to start service. Possible reasons are:
- If you were trying to access a developer service (developer subcommand):
    - Make sure the DeveloperDiskImage/PersonalizedImage is mounted via:
      > python3 -m pymobiledevice3 mounter auto-mount

    - If your device iOS version >= 17.0:
        - Make sure you passed the --rsd option to the subcommand
          https://github.com/doronz88/pymobiledevice3#working-with-developer-tools-ios--170

- Apple removed this service

- A bug. Please file a bug report:
  https://github.com/doronz88/pymobiledevice3/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

I don´t know what to do, I am new on this, I just wanted to enable JIT on a emulator to play 3DS games

PD: Thanks in advance and sorry for the bad english, I speak spanish... ;)

**Comment by fritzlb** [comment]
did you try completely rebooting your PC by clicking "restart"? I did have a similar issue, for me rebooting fixed it. 
Shutdown and boot isn't the same btw
