### ISSUE TITLE
ERROR WeTestUsbFilter driver

### ISSUE THREAD

**Issue by JP0S** [fritzlb/iOS17-JIT-WIN#20]
I am Japanese, so please understand that I sometimes use translations.

Getting bundle ID...
Got bundle ID: me.oatmealdome.DolphiniOS-njb-patreon-beta.R3NW66986U
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
It seems like your device isn't connected. : [b'\x1b[32m2024-03-22 18:32:03\x1b[0m \x1b[35mPC\x1b[0m \x1b[34mwintun[4816]\x1b[0m \x1b[1;30mINFO\x1b[0m WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.\r\n', b'\x1b[32m2024-03-22 18:32:03\x1b[0m \x1b[35mPC\x1b[0m \x1b[34mwintun[4816]\x1b[0m \x1b[1;30mINFO\x1b[0m WeTestUsbNcm driver use current version: 11.36.59.886, [11.36.59.886] tested.\r\n', b'\x1b[32m2024-03-22 18:32:03\x1b[0m \x1b[35mPC\x1b[0m \x1b[34mwintun[4816]\x1b[0m \x1b[1;30mINFO\x1b[0m use existing WeTestUsbFilter driver.\r\n', b'\x1b[32m2024-03-22 18:32:03\x1b[0m \x1b[35mPC\x1b[0m \x1b[34mwintun[4816]\x1b[0m \x1b[1;30mINFO\x1b[0m use existing WeTestUsbNcm driver.\r\n', b'\x1b[32m2024-03-22 18:32:05\x1b[0m \x1b[35mPC\x1b[0m \x1b[34m__main__[4816]\x1b[0m \x1b[1;30mERROR\x1b[0m \x1b[31mDevice is not connected\x1b[0m\r\n']

**Comment by fritzlb** [comment]
Great to see my script is even being used in Japan! :)
Apparently this connection issue sometimes occurs. If iTunes detects the device there’s probably something wrong with the WeTestUSB driver, another user did solve a similar problem by uninstalling the usbncm and Apple usb drivers, they should automatically reinstall if you plug in the device again. 
Could you maybe try that?

**Comment by JP0S** [comment]
I tried uninstalling it, but I guess I did it wrong and couldn't do it.

**Comment by fritzlb** [comment]
First of all, does iTunes detect your iOS device? If not it might be the cable. 
For uninstalling drivers I like to use device manager, there should show up two Ethernet ncm devices and one apple device if you plug in your iPhone/iPad. Right clicking those entries and selecting uninstall should be enough. Then, disconnect your device, reboot the PC and plug it back in

**Comment by fritzlb** [comment]
Good news: someone managed to fix this. There's a link to the according comment in the Readme :)
