### ISSUE TITLE
Device is not connected

### ISSUE THREAD

**Issue by nMicky7** [fritzlb/iOS17-JIT-WIN#22]
Hello, i have an iPad Air 5 with iOS 17.4.1, i did everything the guide says but i've got this error:

Getting bundle ID...
DEBUG mode specified.
Got bundle ID: com.utmapp.UTM.63TK469236
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
It seems like your device isn't connected. : [b'\x1b[32m2024-03-22 19:59:32\x1b[0m \x1b[35mMickyPC\x1b[0m \x1b[34mwintun[11868]\x1b[0m \x1b[1;30mINFO\x1b[0m WeTestUsbNcm driver use current version: 11.38.34.492, [11.36.59.886] tested.\r\n', b'\x1b[32m2024-03-22 19:59:32\x1b[0m \x1b[35mMickyPC\x1b[0m \x1b[34mwintun[11868]\x1b[0m \x1b[1;30mINFO\x1b[0m WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.\r\n', b'\x1b[32m2024-03-22 19:59:32\x1b[0m \x1b[35mMickyPC\x1b[0m \x1b[34mwintun[11868]\x1b[0m \x1b[1;30mINFO\x1b[0m use existing WeTestUsbFilter driver.\r\n', b'\x1b[32m2024-03-22 19:59:32\x1b[0m \x1b[35mMickyPC\x1b[0m \x1b[34mwintun[11868]\x1b[0m \x1b[1;30mINFO\x1b[0m use existing WeTestUsbNcm driver.\r\n', b'\x1b[32m2024-03-22 19:59:34\x1b[0m \x1b[35mMickyPC\x1b[0m \x1b[34m__main__[11868]\x1b[0m \x1b[1;30mERROR\x1b[0m \x1b[31mDevice is not connected\x1b[0m\r\n']

iTunes and AltServer can see the device. How can I solve this ?

**Comment by fritzlb** [comment]
There are currently many reports with this issue. While I personally cannot reproduce this, I've got one report from someone stating they could solve it by uninstalling the USB ncm drivers in device manager and then reconnecting the device. This should reinstall them automatically.
Also, third party anti-virus tools might cause issues as well as a misconfigured windows firewall.
Could you maybe try to uninstall the drivers and report back if it worked?

**Comment by nMicky7** [comment]
When I go to device manager I have these two drivers:

![a](https://github.com/fritzlb/iOS17-JIT-WIN/assets/59706597/6a756edc-2bc4-4b2b-bbb2-13772002e0bb)

then I right click and uninstall on both and restart the PC. As soon as I plug the iPad back in, the two drivers appear almost instantly (as if they haven't actually been uninstalled at all). I try to run the program again but it still doesn't work.

**Comment by fritzlb** [comment]
I see, then the drivers are probably fine.
Yesterday, a comment under the video suggested ejecting the device in itunes, then rebooting and reconnecting it. Again, I have no idea if that could work but I'd appreciate it if you could give it a try and report again if it changed anything :)

**Comment by nMicky7** [comment]
Apparently I solved it by closing all iTunes processes from the task manager and reopening iTunes, I don't think it's a permanent solution anyway.
I don't know if it's a JIT or UTM problem, but even though it was active, the application crashed and was very slow, when I unplugged the cable it didn't work anymore, so for now I've given up on it while waiting for the official release.
Thanks anyway for the help!

**Comment by fritzlb** [comment]
Thanks for the information, I'll add that to the Readme. Did the script say done? If so the app shouldn't crash if you disconnect the cable, else something went really wrong. If the script isn't done yet disconnecting the cable will result in a crash, that's to be expected. 
Also, the script opens the app which might appear as crashing.

Oh and every JIT implementation isn't a permanent solution, for that either something like trollstore, a jailbreak or official support by Apple would be required.
