### ISSUE TITLE
error: attach failed: attach failed

### ISSUE THREAD

**Issue by JojoZockt** [fritzlb/iOS17-JIT-WIN#23]
Getting bundle ID...
DEBUG mode specified.
Got bundle ID: net.kdt.pojavlauncher
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd59:f83e:21b9::1 58210
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
2024-03-23 19:16:55 DESKTOP-8L5P9C0 pymobiledevice3.cli.mounter[13544] INFO DeveloperDiskImage mounted successfully

Mounted Disk image.
Starting app...
(b'Process launched with pid 433\r\n', b'')
Started app. PID: 433
Starting debug server...
(b"\r\nFollow the following connections steps from LLDB:\r\n\r\n(lldb) platform select remote-ios\r\n(lldb) target create /path/to/local/application.app\r\n(lldb) script lldb.target.module[0].SetPlatformFileSpec(lldb.SBFileSpec('/private/var/containers/Bundle/Application/<APP-UUID>/application.app'))\r\n(lldb) process connect connect://[fd59:f83e:21b9::1]:49253   <-- ACTUAL CONNECTION DETAILS!\r\n(lldb) process launch\r\n\r\n", b'')
Started debug server with connection details: [fd59:f83e:21b9::1]:49253
Run debugging commands...
This might take a few minutes.
(lldb) command source -s 0 cmdfile.txt
Executing commands in 'C:\Users\Anwender\Desktop\IOS17-~1\cmdfile.txt'.
(lldb) gdb-remote [fd59:f83e:21b9::1]:49253
(lldb) settings set target.memory-module-load-level minimal
(lldb) attach -p 433
 error: attach failed: attach failed (Not allowed to attach to process.  Look in the console messages (Console.app), near the debugserver entries, when the attach failed.  The subsystem that denied the attach permission will likely have logged an informative message about why it was denied.)

done.

Restarting PC and device + reinstall didn't fix the issue. AV and firewall deactivated.

**Comment by fritzlb** [comment]
This is really interesting. How exactly did you sideload PojavLauncher?

**Comment by fritzlb** [comment]
I‘m not 100% certain but my best guess is you didn’t use AltStore or sideloadly but instead… something else, potentially an enterprise signing service or even a jailbreak because of the bundle ID?
For JIT to work you do need an app signed using a developer certificate.

**Comment by JojoZockt** [comment]
I used ESign with a paid developer cert

**Comment by fritzlb** [comment]
Yeah, no, sorry. Esign doesn't work with UTM afaik.  Please use a supported install method (or stick to the slow UTM SE). 
I'll have to close this now, if you do have any further issues feel free to open a new one :)

**Comment by eris-webserv** [comment]
Same issue on iOS 17.0.3 using Feather with a paid Apple development certificate
