### ISSUE TITLE
open terminal here.bat doesn't open

### ISSUE THREAD

**Issue by beenycool** [fritzlb/iOS17-JIT-WIN#29]
when I try to open the open terminal here.bat, it appears for a split-second, then disappears. I don't have an antivirus enabled, I've tried to restart multiple times, but nothing worked. Thanks in advance.

**Comment by beenycool** [comment]
update: I copied the code from the git repo and I opened a cmd terminal in the \iOS17-JIT-WIN-main folder. I then pasted the code in and this came out: The system cannot find the path specified.

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.

**Comment by fritzlb** [comment]
Did you extract the zip file? And does the path to the folder contain any special characters or is longer than 256 characters?
Also, idk if the script works if you’re not logged in as administrator bc I was too lazy. As admin rights are required anyway that shouldn’t really affect anyone.

**Comment by fritzlb** [comment]
The only thing the script does is open a terminal window as administrator in the according location, you could try doing that manually. Open windows terminal (or cmd) as admin and use the cd command.
Also the script relies on vbs for getting admin privileges, if that is being blocked on your system it won’t work

**Comment by beenycool** [comment]
thanks for your help it worked! keep it up
