### ISSUE TITLE
CMD ERROR: unable to find specified path

### ISSUE THREAD

**Issue by Incompetenteh** [fritzlb/iOS17-JIT-WIN#3]
Hi, when i try to open the cmd named "open terminal here.bat", it pops up and immediately closes. But if i try entering the commands manually it says 'unable to find specified path' or something like that. How can i fix?

**Comment by fritzlb** [comment]
Could you open cmd.exe, copy the "open terminal here.bat" as path and paste it into cmd, then post the output?

**Comment by fritzlb** [comment]
from (probably) your youtube comment it seems like you already solved it, so I'm going to close this for now :)
