### ISSUE TITLE
It looks like your device isn't connected.

### ISSUE THREAD

**Issue by system-jiangnan** [fritzlb/iOS17-JIT-WIN#30]
Hi.
That's right, it's me again:(
Here's the code for the error:

Getting bundle ID...
Got bundle ID: net.kdt.pojavlauncher.NZK3UY8AAX
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
It seems like your device isn't connected. : [b'\x1b[32m2024-03-30 16:38:06\x1b[0m \x1b[35mDESKTOP-CT9FD1O\x1b[0m \x1b[34m__main__[1716]\x1b[0m \x1b[1;30mERROR\x1b[0m \x1b[31mDevice is not connected\x1b[0m\r\n']

I tried the method you offered, but it didn't work.
Because my computer only supports the USB port, I can't use the original charging cable.

**Comment by fritzlb** [comment]
It seems like the driver hasn’t been correctly installed. You could try running “python -m pymobiledevice3 bonjour” in a terminal and see if that triggers driver installation

**Comment by system-jiangnan** [comment]
I just reinstalled pymobiledevice3. I can connect it. But at the time of 'done', nothing changed on my iPad. It could be a problem with my data cable, it has a broken place in one place. But iTunes can still recognize my iPad with this cable.

**Comment by fritzlb** [comment]
How did you install pojavlauncher?
Before the done pojavlauncher should freeze for about 30s, but that only happens if you installed the correct version (link to that in the Readme) using a supported install method

**Comment by system-jiangnan** [comment]
I don't quite understand what you mean.
I'm using the pojavlauncher version you recommended.
After the program opens the pojavlauncher, I can operate the poajvlauncher freely.

**Comment by fritzlb** [comment]
So tapping play actually starts the game? Then everything works, even if pojavlauncher still reports JIT could not be enabled in the launcher screen

**Comment by fritzlb** [comment]
Please explain. While English isn’t my first language, I’m trying my best to understand the issue you’re experiencing. 
According to you, the script says “done” after it opened pojavlauncher and the app works as expected, right?
If tapping “play” results in Minecraft starting, everything went right, even if pojavlauncher has a small message in the bottom left corner saying JIT couldn’t be activated. That is a pojavlauncher bug, I can’t do anything about that. 
If tapping play results in a centered, white pop up that says waiting for JIT, even if the script opened the app and says “done” then there’s a high probability you haven’t been using a supported installation method (AltStore or sideloadly, probably sidestore works too but I didn’t test that).
Or in other words: What changes were you expecting?

**Comment by zrm9901** [comment]
idk if comments show up in closed issues so I'll post it again here; So I am getting this error, I have tried restarting and installing it again, reinstalling the drivers, and using different usb cables/ports. I am on 17.4.1 is it not possible on this veresion?

**Comment by fritzlb** [comment]
As there’s no reply, I‘ll close this for now. If it still doesn’t work and you think the script might be the problem, feel free to open a new one :)

**Comment by 2woke4lyfe50** [comment]
The fix for this is you have to turn off facial recognition and your Lock Screen code…worked for me!…after that run everything the same way
