### ISSUE TITLE
cannot download pillow

### ISSUE THREAD

**Issue by SoldJewel16434** [fritzlb/iOS17-JIT-WIN#32]
it says:ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    Pillow from https://files.pythonhosted.org/packages/ef/43/c50c17c5f7d438e836c169e343695534c38c77f60e7c90389bd77981bc21/pillow-10.3.0.tar.gz (from pymobiledevice3==2.46.2):
        Expected sha256 9d2455fbf44c914840c793e89aa82d0e1763a14253a000743719ae5946814b2d
             Got        04e9033fec49eb42cdd732537e7ab8a72cea568b6f4f7030f43d15dabdc849e6

**Comment by fritzlb** [comment]
That’s an installation error which happens when trying to download a package pymobiledevice3 lists as requirement. 

Is there any chance your internet access is limited? If so, try to use a VPN or maybe Tor or sth

**Comment by SoldJewel16434** [comment]
ok,i'll try

**Comment by SoldJewel16434** [comment]
a new problem:(   QwQ

**Comment by SoldJewel16434** [comment]
> a new problem:( QwQ

![Uploading IMG_3773.png…]()

**Comment by SoldJewel16434** [comment]
![IMG_3773](https://github.com/fritzlb/iOS17-JIT-WIN/assets/165535734/0c8b2cdf-59a5-458d-b305-eafa1b11ee26)

**Comment by fritzlb** [comment]
That's still happening during the installation, right? Try running pip install pymobiledevice3==2.46.2 again in a terminal.
Could I ask from which country you're trying to install this? In case the internet is censored in your country or region errors are expected. For example the Great Firewall in china is known to cause issues

**Comment by SoldJewel16434** [comment]
Obviously,China


> That's still happening during the installation, right? Try running pip install pymobiledevice3==2.46.2 again in a terminal. Could I ask from which country you're trying to install this? In case the internet is censored in your country or region errors are expected. For example the Great Firewall in china is known to cause issues

**Comment by SoldJewel16434** [comment]
> That's still happening during the installation, right? Try running pip install pymobiledevice3==2.46.2 again in a terminal. Could I ask from which country you're trying to install this? In case the internet is censored in your country or region errors are expected. For example the Great Firewall in china is known to cause issues

I’ll try it the next day. Thanks

**Comment by SoldJewel16434** [comment]
I can’t open the terminal too,although I run it as an admin but I don’t know if I blocked the VBS.I’m just an amateur.:(
(My English isn’t very good,sorry.)

**Comment by fritzlb** [comment]
I fear there’s nothing I can currently do to help you. I added a short notice to the readme to warn others about potential issues with installation in china.
