### ISSUE TITLE
Other type of Device is not connected

### ISSUE THREAD

**Issue by SenyxLois** [fritzlb/iOS17-JIT-WIN#37]
Getting bundle ID...
DEBUG mode specified.
Got bundle ID: net.kdt.pojavlauncher.9MTS8PSUG9
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: macaddr theport
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
2024-04-14 02:05:25 DESKTOP-SENYXPC __main__[6856] ERROR Device is not connected

**Comment by fritzlb** [comment]
It seems like there’s something wrong maybe with iTunes. Does iTunes detect your device?
Also if you‘d like to keep your privacy, please censor the letter combination at the end of your bundle ID as that’s unique. Censoring the ipv6 address and port (nope, that’s not a MAC address) doesn’t help anything except maybe making debugging this harder than it has to be. Also that port and address change all the time and can only be accessed by plugging in your idevice. 
Also I wonder, is there anything else in the log? It feels like a few lines of maybe important stuff is missing

**Comment by SenyxLois** [comment]
> It seems like there’s something wrong maybe with iTunes. Does iTunes detect your device? Also if you‘d like to keep your privacy, please censor the letter combination at the end of your bundle ID as that’s unique. Censoring the ipv6 address and port (nope, that’s not a MAC address) doesn’t help anything except maybe making debugging this harder than it has to be. Also that port and address change all the time and can only be accessed by plugging in your idevice. Also I wonder, is there anything else in the log? It feels like a few lines of maybe important stuff is missing

Found out the problem, thank you though. Its actually because pojav was running first so i just need to close the app then run the script all good

**Comment by fritzlb** [comment]
In theory that shouldn't make a difference, but thanks for the update! I'm glad it works for you :)
I'll close this for now, if there's anything else feel free to open another issue
