### ISSUE TITLE
Device is not connected!

### ISSUE THREAD

**Issue by Newvixestar** [fritzlb/iOS17-JIT-WIN#38]
Getting bundle ID...
Got bundle ID: me.oatmealdome.dolphinios-njb
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
It seems like your device isn't connected. : [b'\x1b[32m2024-04-17 21:45:25\x1b[0m \x1b[35mHome\x1b[0m \x1b[34mwintun[7888]\x1b[0m \x1b[1;30mINFO\x1b[0m WetestUsbFilter driver use current version: [11.36.33.666](tel:11.36.33.666), [[11.36.33.666](tel:11.36.33.666)] tested.\r\n', b'\x1b[32m2024-04-17 21:45:30\x1b[0m \x1b[35mHome\x1b[0m \x1b[34mwintun[7888]\x1b[0m \x1b[1;30mINFO\x1b[0m use existing WeTestUsbFilter driver.\r\n', b'\x1b[32m2024-04-17 21:45:30\x1b[0m \x1b[35mHome\x1b[0m \x1b[34mwintun[7888]\x1b[0m \x1b[1;30mINFO\x1b[0m WeTestUsbNcm driver not exists or expired.\r\n', b'\x1b[32m2024-04-17 21:45:30\x1b[0m \x1b[35mHome\x1b[0m \x1b[34mwintun[7888]\x1b[0m \x1b[1;30mINFO\x1b[0m Unsupported windows 10 version (10.0.17134), only support 10.0.19041+\r\n', b'\x1b[32m2024-04-17 21:45:32\x1b[0m \x1b[35mHome\x1b[0m \x1b[34m__main__[7888]\x1b[0m \x1b[1;30mERROR\x1b[0m \x1b[31mDevice is not connected\x1b[0m\r\n']

Help me fix plz

**Comment by fritzlb** [comment]
If I interpret the log correctly there's a chance your windows system is outdated. It seems like your PC didn't properly update since 2018, that's like 6 years ago!
Which version of windows 10 are you running? 1803?
For this to work you need at least version 2004 from early 2020. 
Also in case you didn't manually censor it the bundle ID you typed in won't work.

**Comment by fritzlb** [comment]
The bundle ID can be obtained from AltStore or sideloadly for example, check the readme. Whatever TikTok tutorial you used wasn’t created by me so I can’t assist on that. In case you‘re using something like esign forget about this project, esign isn’t compatible with JIT. 

Updating the PC (or using another one that’s more up to date) is necessary to continue.

**Comment by fritzlb** [comment]
I'll close this for now as it's pretty clear that the issue hasn't got anything to do with the script. If there's something else not working, feel free to open a new one :)
