### ISSUE TITLE
Applications have JIT disabled when Closed

### ISSUE THREAD

**Issue by CitrusLinux** [fritzlb/iOS17-JIT-WIN#50]
I have Sidestore with this application, when i close the app with JIT (PojavLauncher) JIT gets disabled.

**Comment by CitrusLinux** [comment]
Wait i may have just realized the issue, ive been using Ethernet when enabling JIT

**Comment by fritzlb** [comment]
While this sucks, it is expected behavior. Over on another issue (idk where anymore, you‘ll find it if you’re interested) is a longer technical explanation on why. 
Long story short: Apple is the culprit here, they do it for „security reasons“

**Comment by CitrusLinux** [comment]
So just a quick question, would there in any way be able to allow JIT to be enabled after app reopens? Using any means possible (except jailbreaking)

**Comment by fritzlb** [comment]
If you're in your home Wifi network and have your PC running try the new sideJIT
