### ISSUE TITLE
"Error launching the app. Did you specify the correct bundle ID?" - Can get JIT-WIN to work. 

### ISSUE THREAD

**Issue by Jabronis18** [fritzlb/iOS17-JIT-WIN#51]
below is the output, not sure how to troubleshoot from here. This is the correct Itunes (not the winstore one) and I believe I've followed all the instructions as written:

C:\PROGRA~1\IOS17-~1>set "params="

C:\PROGRA~1\IOS17-~1>cd /d "C:\PROGRA~1\IOS17-~1\"   && (if exist "C:\Users\jlebaron\AppData\Local\Temp\getadmin.vbs" del "C:\Users\jlebaron\AppData\Local\Temp\getadmin.vbs"  )  && fsutil dirty query C:   1>nul 2>nul  || (echo Set UAC = CreateObject("Shell.Application") : UAC.ShellExecute "cmd.exe", "/k cd ""C:\PROGRA~1\IOS17-~1\"" && ""C:\PROGRA~1\IOS17-~1\OPENTE~1.BAT"" ", "", "runas", 1   1>>"C:\Users\jlebaron\AppData\Local\Temp\getadmin.vbs"  && "C:\Users\jlebaron\AppData\Local\Temp\getadmin.vbs"   && exit /B  )

C:\PROGRA~1\IOS17-~1>python jit_enabler_better.py njb.beta.584PAN8Z8K True
Getting bundle ID...
DEBUG mode specified.
Got bundle ID: njb.beta.584PAN8Z8K
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd09:33fd:60e8::1 50129
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
2024-04-24 17:56:10 AST-1833 pymobiledevice3.cli.mounter[10040] ERROR DeveloperDiskImage already mounted

Diskimage already mounted.
Starting app...
(b'', b'Traceback (most recent call last):\r\n  File "<frozen runpy>", line 198, in _run_module_as_main\r\n  File "<frozen runpy>", line 88, in _run_code\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pymobiledevice3\\__main__.py", line 156, in <module>\r\n    main()\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pymobiledevice3\\__main__.py", line 98, in main\r\n    cli()\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\click\\core.py", line 1157, in __call__\r\n    return self.main(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\click\\core.py", line 1078, in main\r\n    rv = self.invoke(ctx)\r\n         ^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\click\\core.py", line 1688, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\click\\core.py", line 1688, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\click\\core.py", line 1688, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\click\\core.py", line 1434, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\click\\core.py", line 783, in invoke\r\n    return __callback(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pymobiledevice3\\cli\\cli_common.py", line 172, in wrap_callback_calling\r\n    callback(service_provider=service_provider, **kwargs)\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pymobiledevice3\\cli\\developer.py", line 198, in launch\r\n    pid = process_control.launch(bundle_id=parsed_arguments[0], arguments=parsed_arguments[1:],\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pymobiledevice3\\services\\dvt\\instruments\\process_control.py", line 74, in launch\r\n    result = self._channel.receive_plist()\r\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 261, in receive_plist\r\n    return self._service.recv_plist(self)[0]\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 438, in recv_plist\r\n    data = archiver.unarchive(data)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 23, in unarchive\r\n    return Unarchive(plist).top_object()\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 267, in top_object\r\n    return self.decode_object(self.top_uid)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 126, in decode_archive\r\n    user_info = archive_obj.decode(\'NSUserInfo\')\r\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 150, in decode\r\n    return self._unarchiver.decode_key(self.object, key)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 226, in decode_key\r\n    return self.decode_object(val)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 109, in decode_archive\r\n    val = archive_obj.decode_index(val_uids[i])\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 147, in decode_index\r\n    return self._unarchiver.decode_object(index)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 126, in decode_archive\r\n    user_info = archive_obj.decode(\'NSUserInfo\')\r\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 150, in decode\r\n    return self._unarchiver.decode_key(self.object, key)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 226, in decode_key\r\n    return self.decode_object(val)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 109, in decode_archive\r\n    val = archive_obj.decode_index(val_uids[i])\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 147, in decode_index\r\n    return self._unarchiver.decode_object(index)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\bpylist2\\archiver.py", line 258, in decode_object\r\n    obj = klass.decode_archive(ArchivedObject(raw_obj, self))\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\jlebaron\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pymobiledevice3\\services\\remote_server.py", line 129, in decode_archive\r\n    raise DvtException(archive_obj.decode(\'NSUserInfo\'))\r\npymobiledevice3.exceptions.DvtException: {\'BSErrorCodeDescription\': \'NotFound\', \'NSLocalizedFailureReason\': \'Application info provider (FBSApplicationLibrary) returned nil for "njb.beta.584PAN8Z8K"\'}\r\n')
Error launching the app. Did you specify the correct bundle ID? : Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 156, in <module>
    main()
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\cli_common.py", line 172, in wrap_callback_calling
    callback(service_provider=service_provider, **kwargs)
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\developer.py", line 198, in launch
    pid = process_control.launch(bundle_id=parsed_arguments[0], arguments=parsed_arguments[1:],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\dvt\instruments\process_control.py", line 74, in launch
    result = self._channel.receive_plist()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 261, in receive_plist
    return self._service.recv_plist(self)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 438, in recv_plist
    data = archiver.unarchive(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 23, in unarchive
    return Unarchive(plist).top_object()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 267, in top_object
    return self.decode_object(self.top_uid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
    user_info = archive_obj.decode('NSUserInfo')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 150, in decode
    return self._unarchiver.decode_key(self.object, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
    return self.decode_object(val)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
    val = archive_obj.decode_index(val_uids[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
    return self._unarchiver.decode_object(index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 126, in decode_archive
    user_info = archive_obj.decode('NSUserInfo')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 150, in decode
    return self._unarchiver.decode_key(self.object, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 226, in decode_key
    return self.decode_object(val)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 109, in decode_archive
    val = archive_obj.decode_index(val_uids[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 147, in decode_index
    return self._unarchiver.decode_object(index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\bpylist2\archiver.py", line 258, in decode_object
    obj = klass.decode_archive(ArchivedObject(raw_obj, self))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jlebaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\services\remote_server.py", line 129, in decode_archive
    raise DvtException(archive_obj.decode('NSUserInfo'))
pymobiledevice3.exceptions.DvtException: {'BSErrorCodeDescription': 'NotFound', 'NSLocalizedFailureReason': 'Application info provider (FBSApplicationLibrary) returned nil for "njb.beta.584PAN8Z8K"'}

C:\PROGRA~1\IOS17-~1>Error launching the app. Did you specify the correct bundle ID? : Traceback (most recent call last):
'Error' is not recognized as an internal or external command,
operable program or batch file.

C:\PROGRA~1\IOS17-~1>  File "<frozen runpy>", line 198, in _run_module_as_main
'File' is not recognized as an internal or external command,
operable program or batch file.

C:\PROGRA~1\IOS17-~1>  File "<frozen runpy>", line 88, in _run_code

**Comment by CitrusLinux** [comment]
This could be a time frame thing as i am ALSO getting a similar error, 
C:\Users\[REDACTED]\Desktop\IOS17-~1\IOS17-~1>python jit_enabler_better.py net.kdt.pojavlauncher.[REDACTED]
Getting bundle ID...
Got bundle ID: net.kdt.pojavlauncher.[REDACTED]
starting tunnel to device...
This might take a while. In case it freezes, either close this window and kill every python process in task manager or simply reboot your PC.
Sucessfully created tunnel: fd77:3911:8fd7::1 56280
Manually trying to mount DeveloperDiskImage (this seems to prevent errors on some systems)...
Diskimage already mounted.
Starting app...
Error launching the app. Did you specify the correct bundle ID? : C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\utils.py:55: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

**Comment by CitrusLinux** [comment]
Im doing some testing right now to see what the issue could be

**Comment by CitrusLinux** [comment]
I think i figured it out, did you ever run install.bat?

**Comment by CitrusLinux** [comment]
Question, did you ever run install.bat? If you didn't you will need to redownload the repository and run that first, disable any antivirus

**Comment by Jabronis18** [comment]
Yep after installing python to PATH I ran install.bat and that seemed to
install properly (it said successfully installed, and then prompted for a
restart) once I rebooted I ran the open terminal here script with the
correct bundle ID and this was the output.

**Comment by CitrusLinux** [comment]
Yep, that is your error, @fritzlb, please close this, run install.bat for proper installation next time

**Comment by CitrusLinux** [comment]
So did you get it fixed?

**Comment by Jabronis18** [comment]
No this was the output after running through those steps.

Thanks,

Jeremy LeBaron

**Comment by JortGibbons** [comment]
I'm having this issue trying to run DolphioniOS

**Comment by Jabronis18** [comment]
That’s the same app I’m trying to run, and experiencing this with both the
Beta and the stable release.

Thanks,

Jeremy LeBaron

**Comment by fritzlb** [comment]
According to the log, there's this short but definitely useful piece of information: {'BSErrorCodeDescription': 'NotFound', 'NSLocalizedFailureReason': 'Application info provider (FBSApplicationLibrary) returned nil for "njb.beta.584PAN8Z8K"'}\r\n')
That means you didn't specify the right bundle ID, probably sth like dolphonios is missing before whatever you entered (no warranty, please re-check by yourself)

**Comment by Jabronis18** [comment]
That was it! I misssd the string above 
![IMG_0126](https://github.com/fritzlb/iOS17-JIT-WIN/assets/101469026/ffc1ffce-cd22-4ad5-9f0d-bfabd46974ec)

**Comment by JortGibbons** [comment]
> That was it! I misssd the string above ![IMG_0126](https://private-user-images.githubusercontent.com/101469026/325644779-ffc1ffce-cd22-4ad5-9f0d-bfabd46974ec.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTU5MDAsIm5iZiI6MTcxNDA1NTYwMCwicGF0aCI6Ii8xMDE0NjkwMjYvMzI1NjQ0Nzc5LWZmYzFmZmNlLWNkMjItNGFkNS05ZjBkLWJmYWJkNDY5NzRlYy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMTQzMzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY3OGU5Yzk5ZDNjNmE4NDhiMDFjMDMxYjM2MGQ5MGY0MDM4Mjk5YWRkM2ExNWJlMmU2Yjk5YjI2ZWRiZWFmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LzCh3pA6gk4xXZi0zd72ye9pwPxgcrNs0FoFfXd43mk)
> 
> kind of silly in hindsight that I missed that

I didn't miss that and still had issues. I'll just start another thread when I get home. I'm also receiving an error on my iPad from Dolphin while trying to run it so mine must be another issue.

**Comment by fritzlb** [comment]
Great that it works now for you :)

> That was it! I misssd the string above ![IMG_0126](https://private-user-images.githubusercontent.com/101469026/325644779-ffc1ffce-cd22-4ad5-9f0d-bfabd46974ec.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTk1NTUsIm5iZiI6MTcxNDA1OTI1NSwicGF0aCI6Ii8xMDE0NjkwMjYvMzI1NjQ0Nzc5LWZmYzFmZmNlLWNkMjItNGFkNS05ZjBkLWJmYWJkNDY5NzRlYy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjVUMTUzNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2VhYTc2ODVhYzcxMGY0YmVlOWJjODY2ODA3MjU2NmM2NzU3N2ZiMzIyMzc4ZWI0ZjdjYzliNWM5Zjc3NGNkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m0nZabof8odqcAqZZJ6aEo94z44ofnjEPDoxzcQGjsg)
> 
> kind of silly in hindsight that I missed that
