### ISSUE TITLE
Error Opening a tunnel (No such command 'start-tunnel'.

### ISSUE THREAD

**Issue by mikeraccoons** [fritzlb/iOS17-JIT-WIN#57]
<img width="659" alt="Screenshot 2024-05-01 194754" src="https://github.com/fritzlb/iOS17-JIT-WIN/assets/154574071/ef57301d-b6ef-460c-b7fe-626e3df73688">

Have yet to see anyone with this issue. Curious to see what might be causing it. Running the script with debug enabled didn't help much

**Comment by fritzlb** [comment]
Did you manually update the version of pymobiledevice3 after running the install scripts or sth? If not, is there any chance the python script has been modified?
Also could you try running 'python -m pymobiledevice3 -h' and post the output here?

**Comment by mikeraccoons** [comment]
I figured it out! I discovered a Reddit thread that had the answer.
/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install -U pymobiledevice3==2.30.0 construct==2.10.69 qh3==0.15.1

I'd installed pymobiledevice3 and construct properly but I guess I had to manually install the qh3 dependency. Works flawlessly now. Thanks for the help!

**Comment by fritzlb** [comment]
I'll add that to the install script, then for future users this bug won't happen again. Thanks for the follow up!

**Comment by fritzlb** [comment]
Okay, I checked. construct should be in the dependencies of pymobiledevice3 and version 2.10.70 from November 2023 works flawlessly, so I won’t change anything for now. I assume something about your installation just went wrong, but now that everything works I‘ll close this for now.
