### ISSUE TITLE
Pojavlauncher Settings

### ISSUE THREAD

**Issue by TEKHD** [fritzlb/iOS17-JIT-WIN#6]
Hello there my friend, I also enabled JIT to Pojavlauncher but when I run the game, it crashes. I am running IOS 17.3.1 on iPhone 15 Pro Max. Did you change some settings in Pojavlauncher in order to make it work?

I also posted a guide on How to Enable JIT using  Windows on Reddit. Here is the Link:

https://www.reddit.com/r/sideloaded/s/A7PDL4dFPv

Please, let me know your Pojavlauncher settings. Mine literally crashes as soon as I hit Play. (JIT perfectly enabled) Thank you!

* I am using the SideStore version of Pojavlauncher.  (v2.2-development) Are you using another IPA?

![image](https://github.com/fritzlb/iOS17-JIT-WIN/assets/46690161/2807649b-3313-459e-a7ac-e2c8172226f6)

![image](https://github.com/fritzlb/iOS17-JIT-WIN/assets/46690161/eb1506ff-1b37-48c5-92bc-8fafddf88038)

![image](https://github.com/fritzlb/iOS17-JIT-WIN/assets/46690161/1615adc1-6341-48c1-9158-c59fcb678aaa)

**Comment by fritzlb** [comment]
That's a pojavlauncher bug with 1.20+
Either use 1.19.X or try a development version of Pojavlauncher.

**Comment by fritzlb** [comment]
I ran into a similar problem: https://github.com/PojavLauncherTeam/PojavLauncher_iOS/issues/644
I'll close this issue now as JIT is working :)
