### ISSUE TITLE
Constantly this one file not found error :(

### ISSUE THREAD

**Issue by Gamebooth** [fritzlb/iOS17-JIT-WIN#63]
Traceback (most recent call last):
  File "C:\Users\hylia\DOWNLO~1\IOS17-~1\IOS17-~1\jit_enabler_better.py", line 141, in <module>
    lldb_process = subprocess.Popen(cmd_lldb, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, text=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hylia\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\hylia\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

- so I've tried several times with the normal and slow installers and keep getting the above every time. 2 hours I've been arguing with it now lol

**Comment by fritzlb** [comment]
Inside the directory the script is in, is there a folder containing llvm? If not did you extract the zip and are you logged in as administrator?

**Comment by Gamebooth** [comment]
The fodler wasn't there at the time.. it is now as i downloaded and extracted without the script as I've seen you mention to someone else. I am admin as there's only me on this machine. That solved this issue but now DolphiniOS keeps force closing when it recognises JIT.. Gonna now try beta version as I've just read someone else had success with this. Think it might be my 14PM being problematic now and not me being thick with the script :)

**Comment by fritzlb** [comment]
Great, let me know if the beta works!

**Comment by Gamebooth** [comment]
Yup, that sorted it. Now just need to remember not to swipe the app closed so I don’t have to keep reconnecting to the laptop lol
