### ISSUE TITLE
device is not connected

### ISSUE THREAD

**Issue by rhee120526** [fritzlb/iOS17-JIT-WIN#86]
my ios/ipados 15.1 used to work but now its not working. plus i tried using all the method but it doesnt work. any solutions? here's the code btw. 

It seems like your device isn't connected. : [b'\x1b[32m2024-09-22 21:00:42\x1b[0m \x1b[35mDESKTOP-U4C7VIU\x1b[0m \x1b[34mwintun[21464]\x1b[0m \x1b[1;30mINFO\x1b[0m WeTestUsbNcm driver use current version: 11.38.34.492, [11.36.59.886] tested.\r\n', b'\x1b[32m2024-09-22 21:00:42\x1b[0m \x1b[35mDESKTOP-U4C7VIU\x1b[0m \x1b[34mwintun[21464]\x1b[0m \x1b[1;30mINFO\x1b[0m WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.\r\n', b'\x1b[32m2024-09-22 21:00:43\x1b[0m \x1b[35mDESKTOP-U4C7VIU\x1b[0m \x1b[34mwintun[21464]\x1b[0m \x1b[1;30mINFO\x1b[0m use existing WeTestUsbFilter driver.\r\n', b'\x1b[32m2024-09-22 21:00:43\x1b[0m \x1b[35mDESKTOP-U4C7VIU\x1b[0m \x1b[34mwintun[21464]\x1b[0m \x1b[1;30mINFO\x1b[0m use existing WeTestUsbNcm driver.\r\n', b'\x1b[32m2024-09-22 21:00:45\x1b[0m \x1b[35mDESKTOP-U4C7VIU\x1b[0m \x1b[34m__main__[21464]\x1b[0m \x1b[1;30mERROR\x1b[0m \x1b[31mDevice is not connected\x1b[0m\r\n']

**Comment by fritzlb** [comment]
If you are still on iOS < 17, Try AltServer, Jitterbug, jitstreamer or sth similar. For iOS 17 and up, there are better alternatives like sidejitserver and jitstreamer 2.0

**Comment by rhee120526** [comment]
ok ill try

**Comment by rhee120526** [comment]
it worked!! thank you!!
