### ISSUE TITLE
pymobiledevice3 not installing after 6 complete installs.

### ISSUE THREAD

**Issue by eyespylimited** [fritzlb/iOS17-JIT-WIN#88]
getting the pymobiledevice3 module not found error. I reinstalled the install.bat 3 times, restarted each time and the same with install_slow.bat. please help!

**Comment by fritzlb** [comment]
I won't be able to help without the exact error messages you're getting, sorry. 
Pymobiledevice3 not found usually means that pymobiledevice3 hasn't been properly installed. The install scripts should do that, but if you're located somewhere internet access is restricted (behind a firewall, in china, russia, ...) that might fail

**Comment by brand175** [comment]
@eyespylimited The latest Python is broken, use 3.12.2 instead

**Comment by eyespylimited** [comment]
Live in the EU, also tried out 3.12.2 and it does not come with this issue!
